const express = require('express');
const bodyParser = require('body-parser');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(express.static('public'));

// Set view engine
app.set('view engine', 'ejs');
app.set('views', path.join(__dirname, 'views'));

// Routes
app.get('/', (req, res) => {
    res.render('index');
});

app.post('/generate', (req, res) => {
    try {
        // Expecting req.body to be an array of { targets, labels }
        const groups = req.body;
        if (!Array.isArray(groups)) throw new Error('Input must be an array');
        const config = generateJSONFileSDConfig(groups);
        res.json({
            success: true,
            config: config
        });
    } catch (error) {
        res.status(400).json({
            success: false,
            error: error.message
        });
    }
});

function generateJSONFileSDConfig(groups) {
    let config = '// Prometheus File Service Discovery Configuration\n// Generated by PFSCGen\n\n';
    config += JSON.stringify(groups, null, 2);
    return config;
}

app.listen(PORT, () => {
    console.log(`PFSCGen server running on http://localhost:${PORT}`);
}); 